version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soundvault-api
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - LYRICS_API_KEY=${LYRICS_API_KEY:-dummy_key_for_development}
      - GENIUS_CLIENT_ID=${GENIUS_CLIENT_ID}
      - GENIUS_CLIENT_SECRET=${GENIUS_CLIENT_SECRET}
      - GENIUS_ACCESS_TOKEN=${GENIUS_ACCESS_TOKEN}
      - JWT_SECRET=${JWT_SECRET:-soundvault_secure_jwt_secret_for_development}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://localhost:3000,http://localhost}
    ports:
      - "8080:8080"
    networks:
      - soundvault-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_GENIUS_CLIENT_ID=${VITE_GENIUS_CLIENT_ID}
        - VITE_GENIUS_CLIENT_SECRET=${VITE_GENIUS_CLIENT_SECRET}
        - VITE_GENIUS_ACCESS_TOKEN=${VITE_GENIUS_ACCESS_TOKEN}
        - VITE_GENIUS_REDIRECT_URI=${VITE_GENIUS_REDIRECT_URI:-http://localhost:5173}
        - VITE_DROPBOX_APP_KEY=${VITE_DROPBOX_APP_KEY}
        - VITE_DROPBOX_APP_SECRET=${VITE_DROPBOX_APP_SECRET}
        - VITE_DROPBOX_REDIRECT_URI=${VITE_DROPBOX_REDIRECT_URI:-http://localhost:5173/auth/dropbox/callback}
    container_name: soundvault-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_GENIUS_CLIENT_ID=${VITE_GENIUS_CLIENT_ID}
      - VITE_GENIUS_CLIENT_SECRET=${VITE_GENIUS_CLIENT_SECRET}
      - VITE_GENIUS_ACCESS_TOKEN=${VITE_GENIUS_ACCESS_TOKEN}
      - VITE_GENIUS_REDIRECT_URI=${VITE_GENIUS_REDIRECT_URI:-http://localhost:5173}
      - VITE_DROPBOX_APP_KEY=${VITE_DROPBOX_APP_KEY}
      - VITE_DROPBOX_APP_SECRET=${VITE_DROPBOX_APP_SECRET}
      - VITE_DROPBOX_REDIRECT_URI=${VITE_DROPBOX_REDIRECT_URI:-http://localhost:5173/auth/dropbox/callback}
    ports:
      - "80:80"
    networks:
      - soundvault-network

networks:
  soundvault-network:
    driver: bridge
